// GENERATED by scripts/product.mjs — do not edit.
//
// Read out of this repository's own source on every build, so a figure on the page cannot
// be true on the day it was typed and quietly wrong afterwards. The copy in site-content.ts
// states the reason; this file states the number.

export interface Verdict {
  /** the enum member, which is also the word a summary prints */
  readonly name: string;
  /** the member's value, which IS the process exit code */
  readonly code: number;
  /** the first sentence of the member's own XML summary */
  readonly meaning: string;
}

export interface Package {
  readonly id: string;
  /** "harness" is taken by the project driving the app; "app" by the app under test */
  readonly takenBy: "harness" | "app";
}

export const product = {
  version: "0.1.0",
  packages: [
    {
      "id": "Winwright",
      "takenBy": "harness"
    },
    {
      "id": "Winwright.InApp",
      "takenBy": "app"
    }
  ] as readonly Package[],
  verdicts: [
    {
      "name": "Passed",
      "code": 0,
      "meaning": "Every assertion ran and every one of them held."
    },
    {
      "name": "Failed",
      "code": 1,
      "meaning": "At least one assertion ran and did not hold."
    },
    {
      "name": "Degraded",
      "code": 2,
      "meaning": "Everything that ran passed, and something could not be evaluated at all."
    },
    {
      "name": "Broken",
      "code": 3,
      "meaning": "The harness broke — something threw, and what it says is about this tool rather than about the application under test."
    }
  ] as readonly Verdict[],
} as const;
